### PR TITLE
MLOPS

### PR DESCRIPTION
**Pull request by MyEvilpumpkin**
- Add DVC for test data
- Refactor apps
- Add Docker to CI
- Refactor tests
- Add data tests

### CODE REVIEW

**Review by glebkov97 — DISMISSED** [review]
nice code, fixed all bugs!

**Review by Al-ta-iR — DISMISSED** [review]
Approved

**Review by Al-ta-iR — DISMISSED** [review]
Approved

**Review by dmitry-filimonov — APPROVED** [review]
Amazing, thanks!

**Review by glebkov97 — APPROVED** [review]
approved

**Pull request merged**
